name: functorch_cud11
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - binutils_impl_linux-64=2.36.1
  - blas=1.0
  - bleach=5.0.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - cffi=1.15.1
  - cudatoolkit=11.3.1
  - curl=7.83.1
  - cycler=0.11.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.0.0
  - expat=2.4.8
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=12.1.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=12.1.0
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=12.1.0
  - harfbuzz=5.1.0
  - htop=3.2.1
  - icu=70.1
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - intel-openmp=2022.0.1
  - ipykernel=6.15.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.15.0
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - jupyterlab_pygments=0.2.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnl=3.7.0
  - libnsl=2.0.0
  - libpng=1.6.37
  - libsanitizer=12.1.0
  - libsodium=1.0.18
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.1.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lxml=4.9.1
  - make=4.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2022.0.1
  - munkres=1.1.4
  - nbclient=0.6.7
  - nbconvert=7.0.0
  - nbconvert-core=7.0.0
  - nbconvert-pandoc=7.0.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - numpy=1.23.2
  - openjpeg=2.5.0
  - openssl=3.0.5
  - packaging=21.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - pango=1.50.9
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2022.2.1
  - pyzmq=23.2.1
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.1.3
  - r-base64enc=0.1_3
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-blob=1.2.3
  - r-boot=1.3_28
  - r-brio=1.1.3
  - r-broom=1.0.1
  - r-bslib=0.4.0
  - r-cachem=1.0.6
  - r-callr=3.7.2
  - r-caret=6.0_93
  - r-cellranger=1.1.0
  - r-class=7.3_20
  - r-cli=3.3.0
  - r-clipr=0.8.0
  - r-cluster=2.1.3
  - r-codetools=0.2_18
  - r-colorspace=2.0_3
  - r-commonmark=1.8.0
  - r-cpp11=0.4.2
  - r-crayon=1.5.1
  - r-crul=1.2.0
  - r-curl=4.3.2
  - r-data.table=1.14.2
  - r-dbi=1.1.3
  - r-dbplyr=2.2.1
  - r-desc=1.4.1
  - r-diffobj=0.3.5
  - r-digest=0.6.29
  - r-dplyr=1.0.10
  - r-dtplyr=1.2.2
  - r-e1071=1.7_11
  - r-ellipsis=0.3.2
  - r-essentials=4.1
  - r-evaluate=0.16
  - r-fansi=1.0.3
  - r-farver=2.1.1
  - r-fastmap=1.1.0
  - r-fontawesome=0.3.0
  - r-forcats=0.5.2
  - r-foreach=1.5.2
  - r-foreign=0.8_82
  - r-formatr=1.12
  - r-fs=1.5.2
  - r-future=1.27.0
  - r-future.apply=1.9.0
  - r-gargle=1.2.0
  - r-generics=0.1.3
  - r-ggplot2=3.3.6
  - r-gistr=0.9.0
  - r-glmnet=4.1_2
  - r-globals=0.16.1
  - r-glue=1.6.2
  - r-googledrive=2.0.0
  - r-googlesheets4=1.0.1
  - r-gower=1.0.0
  - r-gtable=0.3.1
  - r-hardhat=1.2.0
  - r-haven=2.5.0
  - r-hexbin=1.28.2
  - r-highr=0.9
  - r-hms=1.1.2
  - r-htmltools=0.5.3
  - r-htmlwidgets=1.5.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.5
  - r-httr=1.4.4
  - r-ids=1.0.1
  - r-ipred=0.9_13
  - r-irdisplay=1.1
  - r-irkernel=1.3
  - r-isoband=0.2.5
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.0
  - r-kernsmooth=2.23_20
  - r-knitr=1.40
  - r-labeling=0.4.2
  - r-later=1.2.0
  - r-lattice=0.20_45
  - r-lava=1.6.10
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.1
  - r-listenv=0.8.0
  - r-lobstr=1.1.2
  - r-lubridate=1.8.0
  - r-magrittr=2.0.3
  - r-maps=3.4.0
  - r-mass=7.3_58.1
  - r-matrix=1.4_1
  - r-memoise=2.0.1
  - r-mgcv=1.8_40
  - r-mime=0.12
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.9
  - r-munsell=0.5.0
  - r-nlme=3.1_159
  - r-nnet=7.3_17
  - r-numderiv=2016.8_1.1
  - r-openssl=2.0.2
  - r-parallelly=1.32.1
  - r-pbdzmq=0.3_7
  - r-pillar=1.8.1
  - r-pkgconfig=2.0.3
  - r-pkgload=1.3.0
  - r-plyr=1.8.7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-proc=1.18.0
  - r-processx=3.7.0
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-progressr=0.10.1
  - r-promises=1.2.0.1
  - r-proxy=0.4_27
  - r-pryr=0.1.5
  - r-ps=1.7.1
  - r-purrr=0.3.4
  - r-quantmod=0.4.20
  - r-r6=2.5.1
  - r-randomforest=4.7_1.1
  - r-rappdirs=0.3.3
  - r-rbokeh=0.5.2
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.9
  - r-readr=2.1.2
  - r-readxl=1.4.1
  - r-recipes=1.0.1
  - r-recommended=4.1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-repr=1.1.4
  - r-reprex=2.0.2
  - r-reshape2=1.4.4
  - r-rlang=1.0.5
  - r-rmarkdown=2.16
  - r-rpart=4.1.16
  - r-rprojroot=2.0.3
  - r-rstudioapi=0.14
  - r-rvest=1.0.3
  - r-sass=0.4.2
  - r-scales=1.2.1
  - r-selectr=0.4_2
  - r-shape=1.4.6
  - r-shiny=1.7.2
  - r-sourcetools=0.1.7
  - r-spatial=7.3_15
  - r-squarem=2021.1
  - r-stringi=1.7.8
  - r-stringr=1.4.1
  - r-survival=3.4_0
  - r-sys=3.4
  - r-testthat=3.1.4
  - r-tibble=3.1.8
  - r-tidyr=1.2.0
  - r-tidyselect=1.1.2
  - r-tidyverse=1.3.2
  - r-timedate=4021.104
  - r-tinytex=0.41
  - r-triebeard=0.3.0
  - r-ttr=0.24.3
  - r-tzdb=0.3.0
  - r-urltools=1.7.3
  - r-utf8=1.2.2
  - r-uuid=1.1_0
  - r-vctrs=0.4.1
  - r-viridislite=0.4.1
  - r-vroom=1.5.7
  - r-waldo=0.4.0
  - r-withr=2.5.0
  - r-xfun=0.32
  - r-xml2=1.3.3
  - r-xtable=1.8_4
  - r-xts=0.12.1
  - r-yaml=2.3.5
  - r-zoo=1.8_10
  - readline=8.1.2
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - sed=4.8
  - send2trash=1.8.0
  - setuptools=65.3.0
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - stack_data=0.5.0
  - statsmodels=0.13.2
  - sysroot_linux-64=2.12
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - tktable=2.10
  - tornado=6.2
  - traitlets=5.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - castle==6.1.0
    - causal-learn==0.1.2.8
    - certifi==2022.6.15
    - charset-normalizer==2.1.1
    - functorch==0.2.1
    - gcastle==1.0.3
    - gputil==1.4.0
    - idna==3.3
    - joblib==1.1.0
    - networkx==2.8.6
    - pandas==1.4.3
    - pydot==1.4.2
    - python-graphviz==0.20.1
    - requests==2.28.1
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - skrebate==0.62
    - threadpoolctl==3.1.0
    - tqdm==4.64.0
    - urllib3==1.26.12
