FROM python:3.11-bullseye
RUN apt update
RUN apt-get -y install python3-pip 
RUN pip3 install causaldag==0.1a163
RUN pip3 install numpy==1.26.4
RUN pip3 install pandas==2.2.2
RUN pip3 install pyAgrum==1.14.0
RUN pip3 install scikit-learn==1.5.0
RUN pip3 install scipy==1.13.1

#RUN pip install contextlib2