rule:
    name:
        module_name
    input:
        data=alg_input_data(),
        edgeConstraints_formatted=edge_constraints_gobnilp
    output:
        adjmat=alg_output_adjmat_path(module_name),
        time=alg_output_time_path(module_name),
        ntests=touch(alg_output_ntests_path(module_name))
    container:
        "docker://bpimages/gobnilp:4347c64"
    script:
        "script.sh"