rule:
    name:
        module_name
    input:
        data=alg_input_data(),
        input_algorithm=input_algorithm,
        edgeConstraints_formatted=edge_constraints_bidag
    output:  
        seqgraph=alg_output_seqgraph_path(module_name),
        time=alg_output_time_path(module_name),
        ntests=touch(alg_output_ntests_path(module_name))
    container:
        "docker://bpimages/bidag:2.1.4"
    script:
        "script.R"
