FROM python:3.7.6

RUN mkdir -p /github/workspace

WORKDIR /github/workspace

RUN pip3 install  --upgrade pip  && \
    pip install torch>=1.9.0  && \
    pip install gcastle==1.0.3rc3

RUN pip install contextlib2
