FROM r-base:4.1.0

RUN apt update -y
RUN apt install -y default-jre
WORKDIR /tetrad
RUN wget https://s01.oss.sonatype.org/content/repositories/releases/io/github/cmu-phil/causal-cmd/1.9.0/causal-cmd-1.9.0-jar-with-dependencies.jar
RUN apt install time

RUN R -e 'install.packages("remotes")' 
RUN R -e 'library(remotes); install_version("argparser", "0.7.1")'
RUN R -e 'library(remotes); install_version("rjson", "0.2.21")'
