FROM python:3.11.4-bullseye

RUN pip install contextlib2
RUN pip install pandas==2.0.3
RUN pip install networkx==3.1
RUN pip install numpy==1.25
RUN pip install scipy==1.11.2
RUN pip install scikit-learn==1.3.0
RUN pip install matplotlib==3.7.2
RUN pip install seaborn==0.12.2
RUN pip install statsmodels==0.14.0
