FROM r-base:4.3.1

RUN R -e "install.packages('remotes')" 
RUN R -e 'library(remotes); install_version("huge", "1.3.5")'
RUN R -e 'library(remotes); install_version("R.utils")'

# Cleanup
RUN rm -rf /tmp/*



