FROM ubuntu:23.04

RUN apt update -y
RUN apt install default-jre -y
RUN apt install time -y
RUN apt install make -y
RUN apt install default-jdk -y
# Make sure this is in the current folder.
COPY jtsampler jtsampler
WORKDIR /jtsampler
RUN make
RUN rm -rf /jtsampler/.git


