FROM python

RUN mkdir git
WORKDIR /git
RUN git clone https://github.com/jmoss20/notears.git
WORKDIR /git/notears

RUN pip install -r requirements.txt
RUN pip install matplotlib pandas
ENV PYTHONPATH /git:/git/notears
RUN apt update && apt install time 
RUN pip install contextlib2
CMD bash
