FROM r-base:4.3.1

RUN R -e "install.packages(\"remotes\")" 
RUN R -e "install.packages(\"R.utils\")" 
RUN R -e "install.packages(\"BiocManager\")" 

RUN R -e "BiocManager::install(\"gRbase\")" 
RUN R -e "BiocManager::install(\"RBGL\")" 
RUN R -e "BiocManager::install(\"Rgraphviz\")"
RUN R -e "BiocManager::install(\"gRain\")" 