FROM ubuntu:23.10

RUN apt update -y
RUN apt install r-base r-base-dev -y

RUN R -e "install.packages(\"install_version\")" --no-save

RUN R -e "install.packages(\"R.utils\", repos=\"https://cran.rstudio.com\")" --no-save
RUN R -e "if (!requireNamespace(\"BiocManager\", quietly = TRUE)) {install.packages(\"BiocManager\", repo=\"http://cran.rstudio.com/\")}" --no-save
RUN R -e "BiocManager::install()" --no-save
RUN R -e "BiocManager::install(\"gRbase\")" --no-save
RUN R -e "BiocManager::install(\"RBGL\")" --no-save
RUN R -e "BiocManager::install(\"Rgraphviz\")" --no-save
RUN R -e "BiocManager::install(\"gRain\")" --no-save

#RUN R -e "install.packages(\"pcalg\")" --no-save
#RUN R -e "install_version(\"pcalg\", \"2.7-8\")" --no-save